C-RISC wiki for creating NEMO 1/12 degree model in Docker container
============================================================

Summary:
*Setup and build XIOS and NEMO on a docker image
*Create 12th degree coordinates file for desired region
*Generate bathymetry file for this region
*Generate a domain configuration file suitable for surge model
*Generate tide boundary conditions
*Generate wind and pressure boundary conditions
*Run with tides and surges forcing
